#!/bin/sh

################################################################################
# Linux Backup
################################################################################
# Copyright (c) 2013 Brett O'Donnell <brett@mrphp.com.au>
# Source Code: https://github.com/cornernote/linux-backup
# License: GPLv3
################################################################################

#
# Monthly Asset Backup
#

BACKUPDAILYDIR=/backup/asset/daily/
BACKUPDIR=/backup/asset/monthly/
BACKUPFILE=`date +"%Y-%m-%d"`.tgz
BACKUPDAYS=365

TAR=`which tar`
FIND=`which find`

# latest daily backup
${TAR} cfzP ${BACKUPDIR}${BACKUPFILE} ${BACKUPDAILYDIR}

# delete old backups
${FIND} ${BACKUPDIR} -mtime +${BACKUPDAYS} -print -exec rm -r {} \;