#!/bin/sh

################################################################################
# Linux Backup
################################################################################
# Copyright (c) 2013 Brett O'Donnell <brett@mrphp.com.au>
# Source Code: https://github.com/cornernote/linux-backup
# License: GPLv3
################################################################################

#
# Daily MySQL Backup
#

BACKUPDIR=/backup/mysql/daily/
BACKUPFOLDER=`date +"%Y-%m-%d"`
BACKUPDAYS=14

MYSQLDUMP=`which mysqldump`
MYDUMPER=`which mydumper`
FIND=`which find`
MKDIR=`which mkdir`

# daily backup
${MKDIR} ${BACKUPDIR}${BACKUPFOLDER}
${MYDUMPER} -t 4 -o ${BACKUPDIR}${BACKUPFOLDER} -c

# delete old backups
${FIND} ${BACKUPDIR} -mtime +${BACKUPDAYS} -delete
${FIND} ${BACKUPDIR} -type d -empty -delete