#!/bin/sh

################################################################################
# Linux Backup
################################################################################
# Copyright (c) 2013 Brett O'Donnell <brett@mrphp.com.au>
# Source Code: https://github.com/cornernote/linux-backup
# License: GPLv3
################################################################################

#
# Monthly MySQL Backup
#

BACKUPDAILYDIR=/backup/mysql/daily/
BACKUPDIR=/backup/mysql/monthly/
BACKUPFOLDER=`date +"%Y-%m-%d"`
BACKUPDAYS=365

FIND=`which find`
RSYNC=`which rsync`

# copy daily backup
${RSYNC} -a ${BACKUPDAILYDIR}${BACKUPFOLDER} ${BACKUPDIR}

# delete old backups
${FIND} ${BACKUPDIR} -mtime +${BACKUPDAYS} -delete
${FIND} ${BACKUPDIR} -type d -empty -delete
