#!/bin/sh

################################################################################
# Linux Backup
################################################################################
# Copyright (c) 2013 Brett O'Donnell <brett@mrphp.com.au>
# Source Code: https://github.com/cornernote/linux-backup
# License: GPLv3
################################################################################

#
# Remote Backup
#

# backup mysql
/usr/bin/rsync -az -e ssh /backup/mysql/daily/`date +"%Y-%m-%d"`/ backup@backup.example.com:~/backup/mysql

# backup asset
/usr/bin/rsync -az -e ssh /backup/asset/daily/ backup@backup.example.com:~/backup/asset