#!/bin/sh

################################################################################
# Linux Backup
################################################################################
# Copyright (c) 2013 Brett O'Donnell <brett@mrphp.com.au>
# Source Code: https://github.com/cornernote/linux-backup
# License: GPLv3
################################################################################

#
# Daily SVN Backup
#

SOURCE=/var/svn/
BACKUPDIR=/backup/svn/daily/

#search in repository folder to find all the repository names
ls -Al --time-style=long-iso ${SOURCE} | grep '^d' | awk '{print $8}' | while read line
do
        #create the backup repository folder if we don't have it.
    if [ ! -d ${BACKUPDIR}${line} ]; then
        mkdir -p ${BACKUPDIR}${line}
    fi

        #taking backup (1 revision per dump)
    svn-backup-dumps --deltas -q -z -c 1 ${SOURCE}${line} ${BACKUPDIR}${line}
done
