#!/bin/sh

################################################################################
# Linux Backup
################################################################################
# Copyright (c) 2013 Brett O'Donnell <brett@mrphp.com.au>
# Source Code: https://github.com/cornernote/linux-backup
# License: GPLv3
################################################################################

#
# Monthly SVN Backup
#

BACKUPDAILYDIR=/backup/svn/daily/
BACKUPDIR=/backup/svn/monthly/
BACKUPFOLDER=`date +"%Y-%m-%d"`
BACKUPDAYS=365

RSYNC=`which rsync`
FIND=`which find`

# copy latest daily backup
${RSYNC} -a ${BACKUPDAILYDIR} ${BACKUPDIR}${BACKUPFOLDER}

# delete old backups
${FIND} ${BACKUPDIR} -type f -mtime +${BACKUPDAYS} -delete
${FIND} ${BACKUPDIR} -type d -empty -delete
